version: '3'
services:
  backend:
    build: .
    ports:
      - "3001:3001"  # Assure-toi que le port 3001 est bien exposé
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/argent-bank  # Exemple si tu utilises MongoDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb_data:
