swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
host: "argentbank-bydelta13-api-c9d02df5fde5.herokuapp.com"
basePath: /api/v1
schemes: 
  - "http"

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: "#/definitions/Login"
      produces:
        - application/json
      responses:
        "200":
          description: Login Successfully
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: "#/definitions/User"
      produces:
        - application/json
      responses:
        "200":
          description: Signup Successfully
          schema:
            $ref: "#/definitions/UserApiResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
      # - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/UserResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: "#/definitions/UserProfile"
      produces:
        - application/json
      responses:
        "200":
          description: User profile retrieved successully
          schema:
            $ref: "#/definitions/UserResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account:
    put:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: User Profile API
      description: API for add account at a user profile
      parameters:
        - in: body
          name: body
          description: account payload
          required: true
          schema:
            $ref: "#/definitions/UserAccount"
      produces:
        - application/json
      responses:
        "200":
          description: add account at a user profile successully
          schema:
            $ref: "#/definitions/accountResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/operations:
    put:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: User Profile API
      description: API for add operation in account at a user profile
      parameters:
        - in: body
          name: body
          description: add operation in account at a user profile
          required: true
          schema:
            $ref: "#/definitions/operation"
      produces:
        - application/json
      responses:
        "200":
          description: add operations at a user profile successully
          schema:
            $ref: "#/definitions/operationResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/operations/description:
    put:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: User Profile API
      description: API for add or update descrition of operations
      parameters:
        - in: body
          name: body
          description: add or update descrition of operations
          required: true
          schema:
            $ref: "#/definitions/description"
      produces:
        - application/json
      responses:
        "200":
          description: add or update descrition successully
          schema:
            $ref: "#/definitions/descriptionResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/operations/category:
    put:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: User Profile API
      description: API for add or update descrition of operations
      parameters:
        - in: body
          name: body
          description: add or update category of operations
          required: true
          schema:
            $ref: "#/definitions/category"
      produces:
        - application/json
      responses:
        "200":
          description: add or update category successully
          schema:
            $ref: "#/definitions/categoryResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

  /user/account/close:
    put:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: User Profile API
      description: API for close account at a user profile
      parameters:
        - in: body
          name: body
          description: close account at a user profile
          required: true
          schema:
            $ref: "#/definitions/visible"
      produces:
        - application/json
      responses:
        "200":
          description: close account at a user profile successully
          schema:
            $ref: "#/definitions/visible"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

/user:
   get:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: Retrieve all confirmed user profiles
      description: API to get all confirmed user profiles
      parameters:
        - in: header
          name: id
          description: ID of the admin
          required: true
          schema:
            type: string
      produces:
        - application/json
      responses:
        "200":
          description: Successfully retrieved user profiles
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
        "401":
          description: Unauthorized, admin not found
        "404":
          description: No users found
        "500":
          description: Internal Server Error

/user/admin:
    put:
      security:
        - Bearer: []
      tags:
        - Admin Module
      summary: User Profile API
      description: API for pagination of user profiles
      parameters:
        - in: body
          name: body
          description: pagination of user profiles
          required: true
          schema:
            $ref: "#/definitions/pagination"
      produces:
        - application/json
      responses:
        "200":
          description: pagination successully
          schema:
            $ref: "#/definitions/paginationResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

/user/budget:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for add or update budget
      parameters:
        - in: body
          name: body
          description: add or update budget
          required: true
          schema:
            $ref: "#/definitions/budget"
      produces:
        - application/json
      responses:
        "200":
          description: add or update budget successully
          schema:
            $ref: "#/definitions/budgetResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

/user/beneficiaires:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for add beneficiaires
      parameters:
        - in: body
          name: body
          description: add beneficiaires
          required: true
          schema:
            $ref: "#/definitions/beneficiaires"
      produces:
        - application/json
      responses:
        "200":
          description: add beneficiaires successully
          schema:
            $ref: "#/definitions/beneficiairesResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

/user/beneficiaires:
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for delete beneficiaire
      parameters:
        - in: body
          name: body
          description: delete beneficiaire
          required: true
          schema:
            $ref: "#/definitions/deleteBeneficiaires"
      produces:
        - application/json
      responses:
        "200":
          description: delete beneficiaire successully
          schema:
            $ref: "#/definitions/deleteBeneficiairesResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

/user/beneficiaires/modifier:
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for update beneficiaire
      parameters:
        - in: body
          name: body
          description: update beneficiaire
          required: true
          schema:
            $ref: "#/definitions/updateBeneficiaires"
      produces:
        - application/json
      responses:
        "200":
          description: update beneficiaire successully
          schema:
            $ref: "#/definitions/updateBeneficiairesResponse"
        "400":
          description: Invalid Fields
        "500":
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header

definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  UserAccount:
    type: object
    properties:
      name:
        type: string
      nbAccount:
        type: string
      solde:
        type: number
      visible:
        type: boolean
      operations:
        type: array
        items:
          type: object
  operation:
    type: object
    properties:
      date:
        type: string
      title:
        type: string
      description:
        type: string
      montant:
        type: number
  description:
    type: object
    properties:
      description:
        type: string
  category:
    type: object
    properties:
      category:
        type: string
  visible:
    type: object
    properties:
      visible:
        type: boolean
  pagination:
    type: object
    properties:
      page:
        type: number
      limit:
        type: number
  budget:
    type: object
    properties:
      budgetCategory:
        type: string
      value:
        type: number
  beneficiaires:
    type: object
    properties:
      name:
        type: string
      rib:
        type: string
  deleteBeneficiaires:
    type: object
    properties:
      id:
        type: string
      iban:
        type: string
  updateBeneficiaires:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      rib:
        type: string


  UserResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  accountResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          name:
            type: string
          nbAccount:
            type: string
          solde:
            type: number
          visible:
            type: boolean
          operations:
            type: array
            items:
              type: object
  operationResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          date:
            type: string
          title:
            type: string
          description:
            type: string
          montant:
            type: number
    descriptionResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          description:
            type: string
    categoryResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          category:
            type: string
    paginationResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          page:
            type: number
          limit:
            type: number
    budgetResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          budgetCategory:
            type: string
          value:
            type: number
    beneficiairesResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          name:
            type: string
          rib:
            type: string
    deleteBeneficiairesResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          name:
            type: string
          iban:
            type: string
    updateBeneficiairesResponse:
      type: string
        properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          name:
            type: string
          rib:
            type: string

